project_name: lwc
archive:
  name_template: "{{ .ProjectName }}-{{ .Version }}-{{ .Os }}-{{ .Arch }}"
checksum:
  name_template: "{{ .ProjectName }}-checksums.txt"
builds:
  - main: cmd/lwc/main.go
    binary: lwc
    goos:
      - windows
      - darwin
      - linux
    goarch:
      - 386
      - amd64
      - arm
      - arm64
nfpm:
  name_template: "{{ .ProjectName }}-{{ .Version }}-{{ .Os }}-{{ .Arch }}"
  homepage: https://github.com/timdp/lwc
  maintainer: Tim De Pauw <hi@tmdpw.eu>
  description: A live-updating version of the UNIX wc command.
  license: MIT
  formats:
    - deb
    - rpm
  bindir: /usr/bin
