version: 2.1
jobs:
  build:
    docker:
      - image: cimg/go:1.18.4
    working_directory: /home/circleci/go/src/github.com/timdp/lwc
    environment:
      TEST_RESULTS: /tmp/test-results
    steps:
      - checkout
      - run: make build_release
      - run: mkdir -p $TEST_RESULTS
      - run: go install github.com/jstemmer/go-junit-report/v2@latest
      - run: go install github.com/mattn/goveralls@latest
      - run: |
          trap "go-junit-report -set-exit-code < $TEST_RESULTS/go-test.out > $TEST_RESULTS/go-test-report.xml" EXIT
          go test -v -cover -race -coverprofile=$TEST_RESULTS/coverage.out ./... | tee $TEST_RESULTS/go-test.out
      - run: goveralls -coverprofile=$TEST_RESULTS/coverage.out -service=circle-ci -repotoken=$COVERALLS_TOKEN
      - run: make test_integration
      - store_test_results:
          path: /tmp/test-results
      - store_artifacts:
          path: /tmp/test-results
          destination: test-results
