version: 2
jobs:
  build:
    docker:
      - image: circleci/golang:1.10.1-stretch
    working_directory: /go/src/github.com/timdp/lwc
    environment:
      TEST_RESULTS: /tmp/test-results
    steps:
      - checkout
      - run: mkdir -p $TEST_RESULTS
      - restore_cache:
          keys:
            - v1-pkg-cache
      - run: go get github.com/jstemmer/go-junit-report
      - run:
          command: |
            trap "go-junit-report < $TEST_RESULTS/go-test.out > $TEST_RESULTS/go-test-report.xml" EXIT
            go test -v $( go list ./... ) | tee $TEST_RESULTS/go-test.out
      - save_cache:
          key: v1-pkg-cache
          paths:
            - /go/pkg
      - store_test_results:
          path: /tmp/test-results
          when: always
      - store_artifacts:
          path: /tmp/test-results
          destination: test-results
          when: always
