version: 2
jobs:
  build:
    docker:
      - image: circleci/golang:1.10.1-stretch
    working_directory: /go/src/github.com/timdp/lwc
    environment:
      TEST_RESULTS: /tmp/test-results
    steps:
      - checkout
      - run: mkdir -p $TEST_RESULTS
      - restore_cache:
          keys:
            - v1-pkg-cache
      - run: curl https://raw.githubusercontent.com/golang/dep/master/install.sh | sh
      - run: dep ensure
      - run: go get github.com/jstemmer/go-junit-report
      - run: go get github.com/mattn/goveralls
      - run: |
          trap "go-junit-report < $TEST_RESULTS/go-test.out > $TEST_RESULTS/go-test-report.xml" EXIT
          go test -v -cover -race -coverprofile=$TEST_RESULTS/coverage.out ./... | tee $TEST_RESULTS/go-test.out
      - run: goveralls -coverprofile=$TEST_RESULTS/coverage.out -service=circle-ci -repotoken=$COVERALLS_TOKEN
      - run: make test/integration
      - save_cache:
          key: v1-pkg-cache
          paths:
            - /go/pkg
      - store_test_results:
          path: /tmp/test-results
          when: always
      - store_artifacts:
          path: /tmp/test-results
          destination: test-results
          when: always
